### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by fq393** [dyboy2017/captcha_check#1]
Traceback (most recent call last):
  File "model_test.py", line 34, in <module>
    image = captcha2text('img/2uB3.jpg')
  File "model_test.py", line 27, in captcha2text
    vector_list = sess.run(predict, feed_dict={x: image_list, keep_prob: 1})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'img/2uB3.jpg'

我自己定义的图片路径 报错诶，不用gen_captcha_text_and_image生成的图片
image = captcha2text('img/2uB3.jpg')

**Comment by msute** [comment]
请问你解决这个问题了吗  我也碰到了
